// need to be able to generate multiple index entry files
// e.g. main, webworker, node, etc.

import { readJSONSync, writeJSONSync } from 'fs-extra/esm';

// sub imports can be generated by finding `init` files? or should it just be a manual list?
const subImports = [
    ['./accessibility', './lib/accessibility'],
    ['./advanced-blend-modes', './lib/advanced-blend-modes'],
    ['./app', './lib/app'],
    ['./dds', './lib/compressed-textures/dds'],
    ['./ktx', './lib/compressed-textures/ktx'],
    ['./ktx2', './lib/compressed-textures/ktx2'],
    ['./basis', './lib/compressed-textures/basis'],
    ['./events', './lib/events'],
    ['./dom', './lib/dom'],
    ['./filters', './lib/filters'],
    ['./math-extras', './lib/math-extras'],
    ['./sprite-tiling', './lib/scene/sprite-tiling'],
    ['./text', './lib/scene/text'],
    ['./text-bitmap', './lib/scene/text-bitmap'],
    ['./text-html', './lib/scene/text-html'],
    ['./graphics', './lib/scene/graphics'],
    ['./mesh', './lib/scene/mesh'],
    ['./prepare', './lib/prepare'],
    ['./unsafe-eval', './lib/unsafe-eval'],
    ['./sprite-nine-slice', './lib/scene/sprite-nine-slice'],
    ['./particle-container', './lib/scene/particle-container'],
];

interface ExportEntry
{
    /**
     * The declarations for TypeScript 5, which has no WebGPU types of its own, so these
     * pull in `@webgpu/types`. TypeScript 6 and above declare the WebGPU globals in their
     * own lib.dom - pulling that in on top would be a duplicate declaration error - so
     * they fall through to `types`, the declarations the library is built against. Must be
     * listed first, conditions are matched in order.
     */
    'types@<6.0'?: string;
    types?: string;
    default: string;
}

interface ExportField
{
    import: ExportEntry;
    require: ExportEntry;
}

const exportFields: Record<string, ExportField> = {
    '.': {
        import: {
            'types@<6.0': './lib/index.legacy.d.ts',
            types: './lib/index.d.ts',
            default: './lib/index.mjs',
        },
        require: {
            'types@<6.0': './lib/index.legacy.d.ts',
            types: './lib/index.d.ts',
            default: './lib/index.js',
        },
    },
    './browser': {
        import: {
            default: './lib/environment-browser/browserAll.mjs',
        },
        require: {
            default: './lib/environment-browser/browserAll.js',
        },
    },
    './webworker': {
        import: {
            default: './lib/environment-webworker/webworkerAll.mjs',
        },
        require: {
            default: './lib/environment-webworker/webworkerAll.js',
        },
    },
    './gif': {
        import: {
            types: './lib/gif/init.d.ts',
            default: './lib/gif/init.mjs',
        },
        require: {
            types: './lib/gif/init.d.ts',
            default: './lib/gif/init.js',
        },
    },
    './html-source': {
        import: {
            types: './lib/html-source/init.d.ts',
            default: './lib/html-source/init.mjs',
        },
        require: {
            types: './lib/html-source/init.d.ts',
            default: './lib/html-source/init.js',
        },
    },
};
const sideEffects = [
    './lib/environment-browser/browserAll.*',
    './lib/environment-webworker/webworkerAll.*',
    './lib/index.*',
    './lib/rendering/init.*',
    './lib/spritesheet/init.*',
    './lib/rendering/renderers/shared/texture/utils/textureFrom.*',
    './lib/gif/init.*',
    './lib/html-source/init.*',
];

for (const [name, path] of subImports)
{
    exportFields[name] = {
        import: {
            default: `${path}/init.mjs`,
        },
        require: {
            default: `${path}/init.js`,
        },
    };
    sideEffects.push(`${path}/init.*`);
}

const pkg = readJSONSync('./package.json');

pkg.exports = exportFields;
pkg.sideEffects = sideEffects;

writeJSONSync('./package.json', pkg, { spaces: 2 });
