import { extensions } from '../extensions/Extensions';
import { BufferImageSource } from '../rendering/renderers/shared/texture/sources/BufferImageSource';
import { ImageSource } from '../rendering/renderers/shared/texture/sources/ImageSource';
import { TextureSource } from '../rendering/renderers/shared/texture/sources/TextureSource';
import { VideoSource } from '../rendering/renderers/shared/texture/sources/VideoSource';
import { Texture } from '../rendering/renderers/shared/texture/Texture';
import { Container } from '../scene/container/Container';
import { Sprite } from '../scene/sprite/Sprite';
import { NineSliceSprite } from '../scene/sprite-nine-slice/NineSliceSprite';
import { TilingSprite } from '../scene/sprite-tiling/TilingSprite';
import { Spritesheet } from '../spritesheet/Spritesheet';
import { serializeBufferImageSourceMixin } from './mixins/serializeBufferImageSourceMixin';
import { serializeContainerMixin } from './mixins/serializeContainerMixin';
import { serializeImageSourceMixin } from './mixins/serializeImageSourceMixin';
import { serializeNineSliceSpriteMixin } from './mixins/serializeNineSliceSpriteMixin';
import { serializeSpriteMixin } from './mixins/serializeSpriteMixin';
import { serializeSpritesheetMixin } from './mixins/serializeSpritesheetMixin';
import { serializeTextureMixin } from './mixins/serializeTextureMixin';
import { serializeTextureSourceMixin } from './mixins/serializeTextureSourceMixin';
import { serializeTilingSpriteMixin } from './mixins/serializeTilingSpriteMixin';
import { serializeVideoSourceMixin } from './mixins/serializeVideoSourceMixin';

export * from './index';

extensions.mixin(Container, serializeContainerMixin);
extensions.mixin(Sprite, serializeSpriteMixin);
extensions.mixin(TilingSprite, serializeTilingSpriteMixin);
extensions.mixin(NineSliceSprite, serializeNineSliceSpriteMixin);
extensions.mixin(Texture, serializeTextureMixin);
extensions.mixin(TextureSource, serializeTextureSourceMixin);
extensions.mixin(ImageSource, serializeImageSourceMixin);
extensions.mixin(VideoSource, serializeVideoSourceMixin);
extensions.mixin(BufferImageSource, serializeBufferImageSourceMixin);
extensions.mixin(Spritesheet, serializeSpritesheetMixin);
