name: '💡 Feature Request'
description: I have a great idea for PixiJS!
title: 'Feature Request: '
labels: ['Feature Request']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for creating a feature request!

        Before opening an issue **please** check if a similar issue exists by
        searching existing issues (<https://github.com/pixijs/pixijs/issues>).

        Before submitting please read:

        Contributors guide: <https://github.com/pixijs/pixijs/blob/dev/.github/CONTRIBUTING.md>
        Code of Conduct: <https://github.com/pixijs/pixijs/blob/dev/.github/CODE_OF_CONDUCT.md>
  - type: textarea
    attributes:
      label: Description
    validations:
      required: true
