import { extensions } from '../../extensions/Extensions';
import { ImageSource } from '../../rendering/renderers/shared/texture/sources/ImageSource';
import { TextureSource } from '../../rendering/renderers/shared/texture/sources/TextureSource';
import { VideoSource } from '../../rendering/renderers/shared/texture/sources/VideoSource';
import { Texture } from '../../rendering/renderers/shared/texture/Texture';
import { Container } from '../../scene/container/Container';
import { FillGradient } from '../../scene/graphics/shared/fill/FillGradient';
import { FillPattern } from '../../scene/graphics/shared/fill/FillPattern';
import { Sprite } from '../../scene/sprite/Sprite';
import { NineSliceSprite } from '../../scene/sprite-nine-slice/NineSliceSprite';
import { TilingSprite } from '../../scene/sprite-tiling/TilingSprite';
import { Text } from '../../scene/text/Text';
import { TextStyle } from '../../scene/text/TextStyle';
import { BitmapText } from '../../scene/text-bitmap/BitmapText';
import { serializeBitmapTextMixin } from './nodes/serializeBitmapText';
import { serializeContainerMixin } from './nodes/serializeContainer';
import { serializeNineSliceSpriteMixin } from './nodes/serializeNineSliceSprite';
import { serializeSpriteMixin } from './nodes/serializeSprite';
import { serializeTextMixin } from './nodes/serializeText';
import { serializeTilingSpriteMixin } from './nodes/serializeTilingSprite';
import { serializeFillGradientMixin } from './resources/serializeFillGradient';
import { serializeFillPatternMixin } from './resources/serializeFillPattern';
import { serializeImageSourceMixin } from './resources/serializeImageSource';
import { serializeTextStyleMixin } from './resources/serializeTextStyle';
import { serializeTextureMixin } from './resources/serializeTexture';
import { serializeTextureSourceMixin } from './resources/serializeTextureSource';
import { serializeVideoSourceMixin } from './resources/serializeVideoSource';

extensions.mixin(Container, serializeContainerMixin);
extensions.mixin(Sprite, serializeSpriteMixin);
extensions.mixin(TilingSprite, serializeTilingSpriteMixin);
extensions.mixin(NineSliceSprite, serializeNineSliceSpriteMixin);
extensions.mixin(Text, serializeTextMixin);
extensions.mixin(BitmapText, serializeBitmapTextMixin);
extensions.mixin(Texture, serializeTextureMixin);
extensions.mixin(TextureSource, serializeTextureSourceMixin);
extensions.mixin(ImageSource, serializeImageSourceMixin);
extensions.mixin(VideoSource, serializeVideoSourceMixin);
extensions.mixin(FillGradient, serializeFillGradientMixin);
extensions.mixin(FillPattern, serializeFillPatternMixin);
extensions.mixin(TextStyle, serializeTextStyleMixin);
