require('./Circle');
require('./Ellipse');
require('./Matrix');
require('./ObservablePoint');
require('./Point');
require('./Polygon');
require('./Rectangle');
require('./RoundedRectangle');
require('./Transform');
