// Generated by CoffeeScript 1.6.3
var Vehicle,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Vehicle = (function(_super) {
  __extends(Vehicle, _super);

  Vehicle.WRAP = "wrap";

  Vehicle.BOUNCE = "bounce";

  Vehicle.prototype.edgeBehavior = Vehicle.BOUNCE;

  Vehicle.prototype.mass = 1.0;

  Vehicle.prototype.maxSpeed = 10;

  Vehicle.prototype.position = null;

  Vehicle.prototype.velocity = null;

  function Vehicle(texture) {
    PIXI.Sprite.call(this, texture);
    this.velocity = new PIXI.Point();
  }

  Vehicle.prototype.update = function() {
    this.velocity.truncate(this.maxSpeed);
    this.position.add(this.velocity);
    this.rotation = this.velocity.angle + 90;
    if (this.edgeBehavior === Vehicle.WRAP) {
      return this.wrap();
    } else if (this.edgeBehavior === Vehicle.BOUNCE) {
      return this.bounce();
    }
  };

  Vehicle.prototype.bounce = function() {
    var w;
    w = window;
    if (this.stage != null) {
      if (this.position.x > w.pixiStageWidth) {
        this.position.x = w.pixiStageWidth;
        this.velocity.x *= -1;
      } else if (this.position.x < 0) {
        this.position.x = 0;
        this.velocity.x *= -1;
      }
      if (this.position.y > w.pixiStageHeight) {
        this.position.y = w.pixiStageHeight;
        return this.velocity.y *= -1;
      } else if (this.position.y < 0) {
        this.position.y = 0;
        return this.velocity.y *= -1;
      }
    }
  };

  Vehicle.prototype.wrap = function() {
    var w;
    w = window;
    if (this.stage != null) {
      if (this.position.x > w.pixiStageWidth) {
        this.position.x = 0;
      }
      if (this.position.x < 0) {
        this.position.x = w.pixiStageWidth;
      }
      if (this.position.y > w.pixiStageHeight) {
        this.position.y = 0;
      }
      if (this.position.y < 0) {
        return this.position.y = w.pixiStageHeight;
      }
    }
  };

  return Vehicle;

})(PIXI.Sprite);
