name: Visual Tests (Pull Request)

on:
  pull_request:
    branches: [ '**' ]

concurrency:
  group: ${{github.workflow}} - ${{github.ref}}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Project
      uses: ./.github/actions/setup

    - name: Test Project
      uses: ./.github/actions/unit
      with:
        type: 'Visuals'
