name: Unit Tests (Pull Request)

on:
  pull_request:
    branches: [ '**' ]

concurrency:
  group: ${{github.workflow}} - ${{github.ref}}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Project
      uses: ./.github/actions/setup

    - name: Lint Project
      uses: ./.github/actions/lint

    - name: Unit Project
      uses: ./.github/actions/unit
      with:
        type: Unit

    - name: Build
      run: npm run dist
