name: Trigger Website Build

on:
  pull_request:
    branches:
      - dev
    types: [ closed ]

jobs:
  trigger-website-build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2.1.1
        with:
          event-type: update-dev
          repository: pixijs/beta.pixijs.com
          token: ${{ secrets.PAT }}
          client-payload: '{"ref": "${{ github.ref }}", "pr_sha": "${{ github.sha }}", "sha": "${{ github.event.pull_request.head.sha }}"}'
